### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by midgod321** [bitxeno/atvloadly#16]
checking afc service status...
afc service OK!
IPA uploading...
                 install INFO  2024-07-27T08:51:50.286 Configuration path: /data/Sideloader
            cli_frontend INFO  2024-07-27T08:51:50.299 Logging in...
 server.developersession INFO  2024-07-27T08:51:50.299 Creating DeveloperSession for kaimda@icloud.com...
            cli_frontend INFO  2024-07-27T08:51:55.931 A code has been sent to your devices, please type it here (type `ENTER` to cancel):
 server.developersession INFO  2024-07-27T08:52:14.237 DeveloperSession created successfully.
                 install INFO  2024-07-27T08:52:14.239 Initiating connection the device (UUID: 00008110-0000595C0ED9801E)
[?25l                 install INFO  2024-07-27T08:52:14.240                                 | 0/100   Fetching development teams
                 install INFO  2024-07-27T08:52:15.207 ###                             | 11/100  List account's development devices
                 install INFO  2024-07-27T08:52:16.255 #######                         | 22/100  Register the current device as a development device
                 install INFO  2024-07-27T08:52:17.180 ##########                      | 33/100  Generating a certificate for Sideloader
                 install INFO  2024-07-27T08:52:21.206 ##############                  | 44/100  Creating App IDs for the application
                sideload INFO  2024-07-27T08:52:22.099 Creating App ID `com.straight-tamago.misakaRS-ATV.HHPUP7GX8R`...
                 install INFO  2024-07-27T08:52:24.855 #################               | 55/100  Creating an application group
                 install INFO  2024-07-27T08:52:26.678 #####################           | 66/100  Manage App IDs and groups
                 install INFO  2024-07-27T08:52:28.666 ########################        | 77/100  Signing the application bundle
                 install INFO  2024-07-27T08:52:28.699 ##########################      | 83/100  Signing the application bundle
                 install INFO  2024-07-27T08:52:28.867 ############################    | 88/100  Signing the application bundle
                 install INFO  2024-07-27T08:52:28.867 ############################    | 88/100  Installing the application on the device
            cli_frontend ERROR 2024-07-27T08:52:29.127 imobiledevice.iMobileDeviceException!(imobiledevice.afc.afc_error_t).iMobileDeviceException at source/imobiledevice/package.d:34: error AFC_E_MUX_ERROR
ERROR: exit status 1
tvos16.2  openwrt  misaka-tvOS

**Comment by bitxeno** [comment]
New version v0.2.3 has print more error log, please try again.

**Comment by midgod321** [comment]
换个账号之后成功了，这个可以关闭了
