### ISSUE TITLE
Anisette Server not detected

### ISSUE THREAD

**Issue by jdmtv001** [bitxeno/atvloadly#20]
I have an anisette server installed (docker) and running. However, it is not being detected. I set the network as a bridge and it is not detetected. I set the network as host and still not detected and rebooted a few times the Linux device, still not detected. 

<img width="562" alt="SCR-20240907-mcks" src="https://github.com/user-attachments/assets/01728174-0694-4e77-8966-11ec0b85f753">

**Comment by bitxeno** [comment]
anisette server is no longer needed
