### ISSUE TITLE
An invalid value 'tv_shelf' was provided for the parameter 'appIdName'.

### ISSUE THREAD

**Issue by hizips** [bitxeno/atvloadly#21]
Any idea how to fix this?

checking afc service status...
afc service OK!
IPA uploading...
                 install INFO  2024-09-08T10:59:18.232 Configuration path: /data/Sideloader
            cli_frontend INFO  2024-09-08T10:59:18.238 Logging in...
 server.developersession INFO  2024-09-08T10:59:18.240 Creating DeveloperSession for hiz****@gmail.com...
 server.developersession INFO  2024-09-08T10:59:20.294 DeveloperSession created successfully.
                 install INFO  2024-09-08T10:59:20.296 Initiating connection the device (UUID: 00008110-0002509A3C0B801E)
[?25l                 install INFO  2024-09-08T10:59:20.297                                 | 0/100   Fetching development teams
                 install INFO  2024-09-08T10:59:21.109 ###                             | 11/100  List account's development devices
                 install INFO  2024-09-08T10:59:22.195 ##########                      | 33/100  Generating a certificate for Sideloader
...d.certificateidentity INFO  2024-09-08T10:59:23.880 Sideload certificate found.
                 install INFO  2024-09-08T10:59:23.881 ##############                  | 44/100  Creating App IDs for the application
                sideload INFO  2024-09-08T10:59:24.730 Creating App ID `com.firecore.infuse.FK485TB2JV.tv-shelf`...
            cli_frontend ERROR 2024-09-08T10:59:25.529 server.developersession.ExceptionType!(server.developersession.DeveloperPortalError).ExceptionType at source/server/developersession.d:74: DeveloperPortalError {
	statusCode = 35
	description = An invalid value 'tv_shelf' was provided for the parameter 'appIdName'.
}
            cli_frontend ERROR 2024-09-08T10:59:25.531 Full exception: server.developersession.ExceptionType!(server.developersession.DeveloperPortalError).ExceptionType@source/server/developersession.d(74): DeveloperPortalError {
	statusCode = 35
	description = An invalid value 'tv_shelf' was provided for the parameter 'appIdName'.
}
----------------
??:? [0x564b92ab2ec6]
??:? [0x564b92ab2b42]
??:? [0x564b92adad16]
??:? [0x564b92abc12f]
??:? [0x564b927f80f6]
??:? [0x564b927da943]
??:? [0x564b928ab675]
??:? [0x564b927d9547]
??:? [0x564b92832bce]
??:? [0x564b927dbd63]
??:? [0x564b927dc21d]
??:? [0x564b92abbdfc]
??:? [0x564b92abbcf6]
??:? [0x564b92abbb4d]
??:? [0x7f2835f61d8f]
??:? __libc_start_main [0x7f2835f61e3f]
??:? [0x564b927d7d14]
ERROR: exit status 1

**Comment by bitxeno** [comment]
`v0.2.4` has fixed.
