### ISSUE TITLE
apple tv os17.5.1  Installation error by openwrt

### ISSUE THREAD

**Issue by abelchu** [bitxeno/atvloadly#22]
pls check the error code, pls help me thx

cli_frontend ERROR 2024-10-20T22:21:17.551 std.file.FileException at /home/runner/ldc2-1.34.0-linux-aarch64/import/std/file.d:2065: /tmp/airon_1729462859995024.ipa/Payload/Airon.app/Frameworks/GCDWebServers.framework/_CodeSignature/CodeResources: No such file or directory
                 install INFO  2024-10-20T22:21:17.580 #########################       | 80/100  Signing the application bundle
                 install INFO  2024-10-20T22:21:17.634 ##########################      | 81/100  Signing the application bundle
                 install INFO  2024-10-20T22:21:17.667 ##########################      | 83/100  Signing the application bundle
ERROR: exit status 1

**Comment by bitxeno** [comment]
You can try remove the ipa  _CodeSignature folder in the framework

**Comment by abelchu** [comment]
> You can try remove the ipa _CodeSignature folder in the framework

thanks!
