### ISSUE TITLE
[Feature] tvOS 17 support

### ISSUE THREAD

**Issue by bao3** [bitxeno/atvloadly#3]
目前可以正常谁，但是中间会报错

>
>Failed to install DeveloperDiskImage.dmg to Name: unknown UDID: 00008110-001930D42181401E. The URL to download the >Developer disk image could not be determined.
>

最终会得到

>Alert: Could not install org.xbmc.kodi-tvos_20.1-0-tvos.ipa to unknown.
    /workdir/build/ldid_patched/ldid.cpp(744): _assert(): Swap(mach_header_->filetype) == MH_EXECUTE || Swap(mach_header_->filetype) == MH_DYLIB || Swap(mach_header_->filetype) == MH_BUNDLE

>Press any key to continue...

然后我的网络应该是可以访问github 的，于是在 container里使用 curl 测试了一下

> curl -L google.com
>curl -L github.com

网络都正常访问。

于是尝试自己手动下载 `https://github.com/pdso/DeveloperDiskImage` 但不知道要下载哪个，放在哪个目录。

**Comment by bitxeno** [comment]
我这边没提示DeveloperDiskImage，不过kodi我试过是没法安装的，你可以试下其他ipa

**Comment by bitxeno** [comment]
找到原因了，16.5以上系统协议变了，没想到刚做完项目就over了🙃，只能等大佬破解协议了

https://github.com/libimobiledevice/libimobiledevice/issues/1452

**Comment by bao3** [comment]
> 找到原因了，16.5以上系统协议变了，没想到刚做完项目就over了🙃，只能等大佬破解协议了
> 
> [libimobiledevice/libimobiledevice#1452](https://github.com/libimobiledevice/libimobiledevice/issues/1452)

泪崩～～～～谢谢更新。那我就暂时只能等待了。

**Comment by bitxeno** [comment]
> 
> 泪崩～～～～谢谢更新。那我就暂时只能等待了。

你有macbook和xcode的话，可以用xcode随便安装一个app到AppleTV，这样xcode会自动加载DeveloperDiskImage，这样就能跳过第一步的错误了，不保证这方法一定有效

**Comment by superxyj2021** [comment]
坐等大佬支持tvos17

**Comment by echoutian** [comment]
坐等佬更新 支持tvos 17

**Comment by CG-man** [comment]
坐等大佬支持更新tvos 17

**Comment by CDWW32** [comment]
Are there any updates on the tvOS17 release?

**Comment by bitxeno** [comment]
新版本已经支持 tvOS17 了

> [!WARNING]  
> 从旧版本升级上来的需要再运行安装ipa流程，重新授权设备。
> Users who have upgraded from the old version need to go through the installation process again and reauthorize atvloadly.
