### ISSUE TITLE
请求支持树莓派3B

### ISSUE THREAD

**Issue by sysytemofxxx** [bitxeno/atvloadly#5]
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.

**Comment by bitxeno** [comment]
我没有arm设备，没法测试，你可以尝试使用dockerfile自己本地构建下看能不能用

**Comment by sysytemofxxx** [comment]
> 我没有arm设备，没法测试，你可以尝试使用dockerfile自己本地构建下看能不能用

谢啦，已经成功
