### ISSUE TITLE
Installed Apps section not updating after Install

### ISSUE THREAD

**Issue by Iridahonda** [bitxeno/atvloadly#7]
I can upload an ipa to the ATV, but after the install the installed apps section remains blank.  Any ideas what I am doing wrong.  Installed ipa works fine on the ATV. Seems the SQLite file app.db isnt being updated.  I am using the latest Docker image

Importing app...
Downloaded app!
Notify: Installing kodi-tvOS to unknown...
    This may take a few seconds.
Received response status code: 200
Received response status code: 200
Signing: Frameworks/TVVLCKit.framework/Info.plist
Signing: Frameworks/TVVLCKit.framework/TVVLCKit

**Comment by bitxeno** [comment]
the installing log show success?  AFAIK kodi is  not supported  by  altserver

**Comment by Iridahonda** [comment]
Sorted - Thany you!
