### ISSUE TITLE
Linux (UBUNTU) Apple TV Detecting but getting stuck on pairing. 

### ISSUE THREAD

**Issue by seroina** [bitxeno/atvloadly#9]
Hey! Everything is working fine, my tv shows up in the web gui but when I try to pair, it just doesn't. 

![image](https://github.com/bitxeno/atvloadly/assets/161231624/57f255b1-b883-4205-9062-fbb86235587c)
![image2](https://github.com/bitxeno/atvloadly/assets/161231624/5c4db653-b6c9-4a79-91da-34e899d78555)

**Comment by seroina** [comment]
I'm not sure if it matters, but I am booting linux up on a usb stick, and using "Try ubuntu".

**Comment by bitxeno** [comment]
can you see the  pin code  show  in AppleTV?

**Comment by seroina** [comment]
no, I do not see the pin code on the apple tv. 
![image](https://github.com/bitxeno/atvloadly/assets/161231624/ea493d07-02f9-46a5-a57d-0b8c1874409b)
I can ping the TV in cmd prompt just fine.

**Comment by bitxeno** [comment]
Are there any error prompts when executing the following command?
```shell
# go inside atvloadly containter shell
docker exec -it <container_id_or_name> /bin/bash

# then execute command
idevice_id
idevicepair pair -u <mac_show_by_idevice_id> -w
```
